In [38]:
import pandas as pd

### Load CSV Dataset into DataFrame

In [39]:
df=pd.read_csv("C:/Users/sheheryarsh/Desktop/JUPYTER-LAB/datasets/employees_data.csv")

In [40]:
print(df)

   Employee_ID              Name   Department   Hire_Date  Salary  \
0         E101        John Smith  Engineering  15/03/2021   85000
1         E102          Jane Doe    Marketing  10/22/2022   65000
2         E103       Mark Taylor        Sales   5/11/2023   72000
3         E104      Sarah Connor           HR   12/1/2024   55000
4         E105         David Lee  Engineering   1/15/2025   90000
..         ...               ...          ...         ...     ...
95        E196    Tristan Knight  Engineering  14/09/2024  112000
96        E197   Serenity Willis        Sales  18/02/2025   83000
97        E198      Ryder Weaver    Marketing   9/24/2021   74000
98        E199  Adeline Johnston        Legal  12/10/2022   96000
99        E200    Sawyer Osborne           IT  21/11/2023   89000

                           Email
0         john.smith@company.com
1           jane.doe@company.com
2        mark.taylor@company.com
3       sarah.connor@company.com
4          david.lee@company.com
..                           ...
95    tristan.knight@company.com
96   serenity.willis@company.com
97      ryder.weaver@company.com
98  adeline.johnston@company.com
99    sawyer.osborne@company.com

[100 rows x 6 columns]

### Locate First Row

In [41]:
print(df.loc[0])

Employee_ID                      E101
Name                       John Smith
Department                Engineering
Hire_Date                  15/03/2021
Salary                          85000
Email          john.smith@company.com
Name: 0, dtype: str

### Locate First Two Rows

In [42]:
df.loc[[0,1,2]]

,Employee_ID,Name,Department,Hire_Date,Salary,Email
0,E101,John Smith,Engineering,15/03/2021,85000,john.smith@company.com
1,E102,Jane Doe,Marketing,10/22/2022,65000,jane.doe@company.com
2,E103,Mark Taylor,Sales,5/11/2023,72000,mark.taylor@company.com

### Display Entire Dataset

In [43]:
print(df.to_string())

   Employee_ID               Name   Department   Hire_Date     Salary                          Email
0         E101         John Smith  Engineering  15/03/2021      85000         john.smith@company.com
1         E102           Jane Doe    Marketing  10/22/2022      65000           jane.doe@company.com
2         E103        Mark Taylor        Sales   5/11/2023      72000        mark.taylor@company.com
3         E104       Sarah Connor           HR   12/1/2024      55000       sarah.connor@company.com
4         E105          David Lee  Engineering   1/15/2025      90000          david.lee@company.com
5         E101         John Smith  Engineering  15/03/2021      85000         john.smith@company.com
6         E107        Alice Brown      Finance  14/04/2022      95000                            NaN
7         E108       Robert Green   Operations         NaN      52000       robert.green@company.com
8         E109        Emily White           IT   9/15/2023  seventy_k        emily.white@company.com
9         E110      Michael Clark  Engineering  31/12/2021     110000            m.clark@company.com
10        E111         Laura Hall    Marketing    2/8/2024      62000         laura.hall@company.com
11        E112         James King          NaN   11/9/2025      81000         james.king@company.com
12        E102           Jane Doe    Marketing  10/22/2022      65000           jane.doe@company.com
13        E114        Emma Watson        Legal  15-05-2023      98000        emma.watson@company.com
14        E115       Daniel Scott           HR  21/06/2022      58000       daniel.scott@company.com
15        E116      Olivia Harris        Sales   10/1/2115      74000      olivia.harris@company.com
16        E117     William Martin           IT  11/12/2023      88000     william.martin@company.com
17        E118       Sophia Clark      Finance  17/02/2021      79000                            NaN
18        E119     Benjamin Lewis   Operations  19/04/2022    fifty_k          ben.lewis@company.com
19        E120   Charlotte Walker          NaN  24/09/2023      82000   charlotte.walker@company.com
20        E115       Daniel Scott           HR  21/06/2022      58000       daniel.scott@company.com
21        E122    Alexander Young  Engineering  12/10/2024      94000         alex.young@company.com
22        E123      Isabella King        Sales    5/3/2025      71000      isabella.king@company.com
23        E124       Lucas Wright    Marketing   1/14/2022      63000       lucas.wright@company.com
24        E125        Amelia Hill        Legal  16/08/2021     105000        amelia.hill@company.com
25        E126        Mason Allen           IT  19-11-2023      89000        mason.allen@company.com
26        E127       Evelyn Baker      Finance   2/12/2024      93000       evelyn.baker@company.com
27        E128       Logan Carter   Operations  27/05/2022      48000                            NaN
28        E129    Harper Mitchell           HR   8/10/2025      59000    harper.mitchell@company.com
29        E130      Jackson Perez  Engineering   12/4/2100     102000      jackson.perez@company.com
30        E131    Abigail Roberts        Sales  15/09/2023      73000    abigail.roberts@company.com
31        E132   Sebastian Turner    Marketing   4/11/2021      68000         seb.turner@company.com
32        E133     Avery Phillips        Legal  18/01/2022      91000     avery.phillips@company.com
33        E134       Mia Campbell  Engineering  10/25/2024      99000       mia.campbell@company.com
34        E135       Ethan Parker      Finance  14/03/2025      97000       ethan.parker@company.com
35        E136         Ella Evans           IT  21/07/2022      86000         ella.evans@company.com
36        E137      Jacob Edwards   Operations   9/12/2023      54000      jacob.edwards@company.com
37        E138      Sofia Collins           HR  17/04/2021      60000      sofia.collins@company.com
38        E139    Jackson Stewart  Engineering  13/11/2022     108000    jackson.stewart@company.com
39        E140        Aria Morris        Sales   12/5/2024      76000        aria.morris@company.com
40        E137      Jacob Edwards   Operations   9/12/2023      54000      jacob.edwards@company.com
41        E142       Logan Rogers    Marketing  14/02/2021      66000       logan.rogers@company.com
42        E143        Camila Reed        Legal   8/16/2022      92000        camila.reed@company.com
43        E144      Benjamin Cook           IT   11/9/2023      87000           ben.cook@company.com
44        E145       Chloe Morgan      Finance  25/04/2024      96000       chloe.morgan@company.com
45        E146        Oliver Bell   Operations  16-10-2025      49000                            NaN
46        E147    Victoria Murphy           HR  19/01/2022      61000    victoria.murphy@company.com
47        E148      Samuel Bailey  Engineering   2/28/2023     101000      samuel.bailey@company.com
48        E149        Zoey Rivera        Sales  13/06/2024      77000        zoey.rivera@company.com
49        E150     Gabriel Cooper    Marketing  17/07/2025      69000     gabriel.cooper@company.com
50        E151    Lily Richardson        Legal  10/15/2021      88000    lily.richardson@company.com
51        E152         Carter Cox           IT  22/11/2022      90000         carter.cox@company.com
52        E153      Hannah Howard      Finance    7/9/2023      94000      hannah.howard@company.com
53        E154          Luke Ward   Operations  15/10/2024      51000          luke.ward@company.com
54        E155     Addison Torres           HR  18/02/2021      62000     addison.torres@company.com
55        E156     Isaac Peterson  Engineering  11/12/2022     104000     isaac.peterson@company.com
56        E157          Nora Gray        Sales  23/05/2023      78000          nora.gray@company.com
57        E158     Julian Ramirez    Marketing   12/4/2024      67000     julian.ramirez@company.com
58        E159        Grace James        Legal  14/06/2025      93000        grace.james@company.com
59        E160       Levi Jenkins           IT   8/27/2021      84000       levi.jenkins@company.com
60        E161         Hazel Diaz      Finance  19/09/2022      95000         hazel.diaz@company.com
61        E162         Ryan Hayes   Operations  10/12/2023      47000         ryan.hayes@company.com
62        E163      Eleanor Myers           HR  14-02-2024      63000      eleanor.myers@company.com
63        E164  Nathan Washington  Engineering  25/04/2025     106000  nathan.washington@company.com
64        E165    Penelope Foster        Sales   3/11/2021      79000    penelope.foster@company.com
65        E166       Aaron Butler    Marketing   12/7/2022      70000       aaron.butler@company.com
66        E155     Addison Torres           HR  18/02/2021      62000     addison.torres@company.com
67        E168     Connor Simmons           IT  10/18/2024      82000     connor.simmons@company.com
68        E169      Stella Hughes      Finance  21/09/2025      98000      stella.hughes@company.com
69        E170   Adrian Henderson   Operations    5/1/2022      53000                            NaN
70        E171    Paisley Alvarez           HR  13/02/2023      64000    paisley.alvarez@company.com
71        E172      Hudson Powell  Engineering   10/3/2024     107000      hudson.powell@company.com
72        E173    Elena Fernandez        Sales  14-04-2025      80000    elena.fernandez@company.com
73        E174        Liam Pierce    Marketing  22/05/2021      71000        liam.pierce@company.com
74        E175      Maya Reynolds        Legal   9/28/2022      91000      maya.reynolds@company.com
75        E176        Leo Griffin           IT  16/10/2023      85000        leo.griffin@company.com
76        E177     Mackenzie Hunt      Finance  12/11/2024      99000     mackenzie.hunt@company.com
77        E178         Eli Hunter   Operations   10/9/2021      50000         eli.hunter@company.com
78        E179    Savannah Tucker           HR  14/01/2022      65000    savannah.tucker@company.com
79        E180        Asher Hicks  Engineering  25/02/2023     109000        asher.hicks@company.com
80        E181    Audrey Crawford        Sales   9/12/2024      81000    audrey.crawford@company.com
81        E182        Miles Ortiz    Marketing  13/03/2025      72000        miles.ortiz@company.com
82        E183     Claire Chapman        Legal  17/04/2021      94000     claire.chapman@company.com
83        E184       Nolan Romero           IT  10/21/2022      86000       nolan.romero@company.com
84        E185     Peyton Hawkins      Finance  14/05/2023      97000     peyton.hawkins@company.com
85        E186      Camden Moreno   Operations  22/06/2024      52000      camden.moreno@company.com
86        E187         Kaylee Fox           HR    9/7/2025      66000         kaylee.fox@company.com
87        E188       Brody Medina  Engineering  11/12/2021     110000       brody.medina@company.com
88        E189    Allison Alvarez        Sales  15/01/2022      82000    allison.alvarez@company.com
89        E190    Julian Caldwell    Marketing  19-02-2023      73000                            NaN
90        E191   Josephine Hansen        Legal  26/03/2024      95000   josephine.hansen@company.com
91        E192   Lincoln Matthews           IT  10/25/2025      87000   lincoln.matthews@company.com
92        E193      Eva Gutierrez      Finance  14/05/2021      98000      eva.gutierrez@company.com
93        E194        Ian Simpson   Operations  23/06/2022      54000        ian.simpson@company.com
94        E188       Brody Medina  Engineering  11/12/2021     110000       brody.medina@company.com
95        E196     Tristan Knight  Engineering  14/09/2024     112000     tristan.knight@company.com
96        E197    Serenity Willis        Sales  18/02/2025      83000    serenity.willis@company.com
97        E198       Ryder Weaver    Marketing   9/24/2021      74000       ryder.weaver@company.com
98        E199   Adeline Johnston        Legal  12/10/2022      96000   adeline.johnston@company.com
99        E200     Sawyer Osborne           IT  21/11/2023      89000     sawyer.osborne@company.com

## Analyzing DataFrame

#### Top first 5 Rows

In [44]:
df.head()

,Employee_ID,Name,Department,Hire_Date,Salary,Email
0,E101,John Smith,Engineering,15/03/2021,85000,john.smith@company.com
1,E102,Jane Doe,Marketing,10/22/2022,65000,jane.doe@company.com
2,E103,Mark Taylor,Sales,5/11/2023,72000,mark.taylor@company.com
3,E104,Sarah Connor,HR,12/1/2024,55000,sarah.connor@company.com
4,E105,David Lee,Engineering,1/15/2025,90000,david.lee@company.com

### Display first 10 Rows

In [45]:
df.head(10)

,Employee_ID,Name,Department,Hire_Date,Salary,Email
0,E101,John Smith,Engineering,15/03/2021,85000,john.smith@company.com
1,E102,Jane Doe,Marketing,10/22/2022,65000,jane.doe@company.com
2,E103,Mark Taylor,Sales,5/11/2023,72000,mark.taylor@company.com
3,E104,Sarah Connor,HR,12/1/2024,55000,sarah.connor@company.com
4,E105,David Lee,Engineering,1/15/2025,90000,david.lee@company.com
5,E101,John Smith,Engineering,15/03/2021,85000,john.smith@company.com
6,E107,Alice Brown,Finance,14/04/2022,95000,NaN
7,E108,Robert Green,Operations,NaN,52000,robert.green@company.com
8,E109,Emily White,IT,9/15/2023,seventy_k,emily.white@company.com
9,E110,Michael Clark,Engineering,31/12/2021,110000,m.clark@company.com

### Display last 10 Rows

In [46]:
df.tail(10)

,Employee_ID,Name,Department,Hire_Date,Salary,Email
90,E191,Josephine Hansen,Legal,26/03/2024,95000,josephine.hansen@company.com
91,E192,Lincoln Matthews,IT,10/25/2025,87000,lincoln.matthews@company.com
92,E193,Eva Gutierrez,Finance,14/05/2021,98000,eva.gutierrez@company.com
93,E194,Ian Simpson,Operations,23/06/2022,54000,ian.simpson@company.com
94,E188,Brody Medina,Engineering,11/12/2021,110000,brody.medina@company.com
95,E196,Tristan Knight,Engineering,14/09/2024,112000,tristan.knight@company.com
96,E197,Serenity Willis,Sales,18/02/2025,83000,serenity.willis@company.com
97,E198,Ryder Weaver,Marketing,9/24/2021,74000,ryder.weaver@company.com
98,E199,Adeline Johnston,Legal,12/10/2022,96000,adeline.johnston@company.com
99,E200,Sawyer Osborne,IT,21/11/2023,89000,sawyer.osborne@company.com

### Print information about the dataframe

In [47]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  100 non-null    str
 1   Name         100 non-null    str
 2   Department   98 non-null     str
 3   Hire_Date    99 non-null     str
 4   Salary       100 non-null    str
 5   Email        94 non-null     str
dtypes: str(6)
memory usage: 4.8 KB
None

### Data Cleaning

#### Remove Empty Cells (rows:6, 7, 11, 17, 19, 27, 25, 69, 89)

In [50]:
df.dropna(inplace=True)

In [53]:
print(df.to_string())

   Employee_ID               Name   Department   Hire_Date     Salary                          Email
0         E101         John Smith  Engineering  15/03/2021      85000         john.smith@company.com
1         E102           Jane Doe    Marketing  10/22/2022      65000           jane.doe@company.com
2         E103        Mark Taylor        Sales   5/11/2023      72000        mark.taylor@company.com
3         E104       Sarah Connor           HR   12/1/2024      55000       sarah.connor@company.com
4         E105          David Lee  Engineering   1/15/2025      90000          david.lee@company.com
5         E101         John Smith  Engineering  15/03/2021      85000         john.smith@company.com
8         E109        Emily White           IT   9/15/2023  seventy_k        emily.white@company.com
9         E110      Michael Clark  Engineering  31/12/2021     110000            m.clark@company.com
10        E111         Laura Hall    Marketing    2/8/2024      62000         laura.hall@company.com
12        E102           Jane Doe    Marketing  10/22/2022      65000           jane.doe@company.com
13        E114        Emma Watson        Legal  15-05-2023      98000        emma.watson@company.com
14        E115       Daniel Scott           HR  21/06/2022      58000       daniel.scott@company.com
15        E116      Olivia Harris        Sales   10/1/2115      74000      olivia.harris@company.com
16        E117     William Martin           IT  11/12/2023      88000     william.martin@company.com
18        E119     Benjamin Lewis   Operations  19/04/2022    fifty_k          ben.lewis@company.com
20        E115       Daniel Scott           HR  21/06/2022      58000       daniel.scott@company.com
21        E122    Alexander Young  Engineering  12/10/2024      94000         alex.young@company.com
22        E123      Isabella King        Sales    5/3/2025      71000      isabella.king@company.com
23        E124       Lucas Wright    Marketing   1/14/2022      63000       lucas.wright@company.com
24        E125        Amelia Hill        Legal  16/08/2021     105000        amelia.hill@company.com
25        E126        Mason Allen           IT  19-11-2023      89000        mason.allen@company.com
26        E127       Evelyn Baker      Finance   2/12/2024      93000       evelyn.baker@company.com
28        E129    Harper Mitchell           HR   8/10/2025      59000    harper.mitchell@company.com
29        E130      Jackson Perez  Engineering   12/4/2100     102000      jackson.perez@company.com
30        E131    Abigail Roberts        Sales  15/09/2023      73000    abigail.roberts@company.com
31        E132   Sebastian Turner    Marketing   4/11/2021      68000         seb.turner@company.com
32        E133     Avery Phillips        Legal  18/01/2022      91000     avery.phillips@company.com
33        E134       Mia Campbell  Engineering  10/25/2024      99000       mia.campbell@company.com
34        E135       Ethan Parker      Finance  14/03/2025      97000       ethan.parker@company.com
35        E136         Ella Evans           IT  21/07/2022      86000         ella.evans@company.com
36        E137      Jacob Edwards   Operations   9/12/2023      54000      jacob.edwards@company.com
37        E138      Sofia Collins           HR  17/04/2021      60000      sofia.collins@company.com
38        E139    Jackson Stewart  Engineering  13/11/2022     108000    jackson.stewart@company.com
39        E140        Aria Morris        Sales   12/5/2024      76000        aria.morris@company.com
40        E137      Jacob Edwards   Operations   9/12/2023      54000      jacob.edwards@company.com
41        E142       Logan Rogers    Marketing  14/02/2021      66000       logan.rogers@company.com
42        E143        Camila Reed        Legal   8/16/2022      92000        camila.reed@company.com
43        E144      Benjamin Cook           IT   11/9/2023      87000           ben.cook@company.com
44        E145       Chloe Morgan      Finance  25/04/2024      96000       chloe.morgan@company.com
46        E147    Victoria Murphy           HR  19/01/2022      61000    victoria.murphy@company.com
47        E148      Samuel Bailey  Engineering   2/28/2023     101000      samuel.bailey@company.com
48        E149        Zoey Rivera        Sales  13/06/2024      77000        zoey.rivera@company.com
49        E150     Gabriel Cooper    Marketing  17/07/2025      69000     gabriel.cooper@company.com
50        E151    Lily Richardson        Legal  10/15/2021      88000    lily.richardson@company.com
51        E152         Carter Cox           IT  22/11/2022      90000         carter.cox@company.com
52        E153      Hannah Howard      Finance    7/9/2023      94000      hannah.howard@company.com
53        E154          Luke Ward   Operations  15/10/2024      51000          luke.ward@company.com
54        E155     Addison Torres           HR  18/02/2021      62000     addison.torres@company.com
55        E156     Isaac Peterson  Engineering  11/12/2022     104000     isaac.peterson@company.com
56        E157          Nora Gray        Sales  23/05/2023      78000          nora.gray@company.com
57        E158     Julian Ramirez    Marketing   12/4/2024      67000     julian.ramirez@company.com
58        E159        Grace James        Legal  14/06/2025      93000        grace.james@company.com
59        E160       Levi Jenkins           IT   8/27/2021      84000       levi.jenkins@company.com
60        E161         Hazel Diaz      Finance  19/09/2022      95000         hazel.diaz@company.com
61        E162         Ryan Hayes   Operations  10/12/2023      47000         ryan.hayes@company.com
62        E163      Eleanor Myers           HR  14-02-2024      63000      eleanor.myers@company.com
63        E164  Nathan Washington  Engineering  25/04/2025     106000  nathan.washington@company.com
64        E165    Penelope Foster        Sales   3/11/2021      79000    penelope.foster@company.com
65        E166       Aaron Butler    Marketing   12/7/2022      70000       aaron.butler@company.com
66        E155     Addison Torres           HR  18/02/2021      62000     addison.torres@company.com
67        E168     Connor Simmons           IT  10/18/2024      82000     connor.simmons@company.com
68        E169      Stella Hughes      Finance  21/09/2025      98000      stella.hughes@company.com
70        E171    Paisley Alvarez           HR  13/02/2023      64000    paisley.alvarez@company.com
71        E172      Hudson Powell  Engineering   10/3/2024     107000      hudson.powell@company.com
72        E173    Elena Fernandez        Sales  14-04-2025      80000    elena.fernandez@company.com
73        E174        Liam Pierce    Marketing  22/05/2021      71000        liam.pierce@company.com
74        E175      Maya Reynolds        Legal   9/28/2022      91000      maya.reynolds@company.com
75        E176        Leo Griffin           IT  16/10/2023      85000        leo.griffin@company.com
76        E177     Mackenzie Hunt      Finance  12/11/2024      99000     mackenzie.hunt@company.com
77        E178         Eli Hunter   Operations   10/9/2021      50000         eli.hunter@company.com
78        E179    Savannah Tucker           HR  14/01/2022      65000    savannah.tucker@company.com
79        E180        Asher Hicks  Engineering  25/02/2023     109000        asher.hicks@company.com
80        E181    Audrey Crawford        Sales   9/12/2024      81000    audrey.crawford@company.com
81        E182        Miles Ortiz    Marketing  13/03/2025      72000        miles.ortiz@company.com
82        E183     Claire Chapman        Legal  17/04/2021      94000     claire.chapman@company.com
83        E184       Nolan Romero           IT  10/21/2022      86000       nolan.romero@company.com
84        E185     Peyton Hawkins      Finance  14/05/2023      97000     peyton.hawkins@company.com
85        E186      Camden Moreno   Operations  22/06/2024      52000      camden.moreno@company.com
86        E187         Kaylee Fox           HR    9/7/2025      66000         kaylee.fox@company.com
87        E188       Brody Medina  Engineering  11/12/2021     110000       brody.medina@company.com
88        E189    Allison Alvarez        Sales  15/01/2022      82000    allison.alvarez@company.com
90        E191   Josephine Hansen        Legal  26/03/2024      95000   josephine.hansen@company.com
91        E192   Lincoln Matthews           IT  10/25/2025      87000   lincoln.matthews@company.com
92        E193      Eva Gutierrez      Finance  14/05/2021      98000      eva.gutierrez@company.com
93        E194        Ian Simpson   Operations  23/06/2022      54000        ian.simpson@company.com
94        E188       Brody Medina  Engineering  11/12/2021     110000       brody.medina@company.com
95        E196     Tristan Knight  Engineering  14/09/2024     112000     tristan.knight@company.com
96        E197    Serenity Willis        Sales  18/02/2025      83000    serenity.willis@company.com
97        E198       Ryder Weaver    Marketing   9/24/2021      74000       ryder.weaver@company.com
98        E199   Adeline Johnston        Legal  12/10/2022      96000   adeline.johnston@company.com
99        E200     Sawyer Osborne           IT  21/11/2023      89000     sawyer.osborne@company.com